create database trivial;
use trivial;

CREATE TABLE Preguntas (
id int auto_increment primary key,
pregunta varchar (1000),
respuesta varchar (1000),
tema varchar (200),
ayuda int
);

INSERT INTO Preguntas (pregunta, respuesta, tema, ayuda) VALUES 
('¿Qué significa el acrónimo SUV?', 'Sport Utility Vehicle', 'Coches', 3),
('¿Qué fabricante de automóviles produce el Mustang?', 'Ford', 'Coches', 1),
('¿En qué año se introdujo el primer automóvil eléctrico producido en masa?', '2010 (Nissan Leaf)', 'Coches', 4),
('¿Qué significa ABS en relación con los frenos de un automóvil?', 'Sistema Antibloqueo de Frenos', 'Coches', 4),
('¿Qué país es conocido por producir la marca de automóviles de lujo Mercedes-Benz?', 'Alemania', 'Coches', 1),
('¿Cuál es la velocidad máxima del Bugatti Veyron Super Sport?', '267 mph (431 km/h)', 'Coches', 6),
('¿Qué fabricante de automóviles japonés produce los modelos Altima y Maxima?', 'Nissan', 'Coches', 1),
('¿En qué año se introdujo por primera vez el Ford Modelo T?', '1908', 'Coches', 1),
('¿Qué significa RPM en el contexto del motor de un automóvil?', 'Revoluciones Por Minuto', 'Coches', 3),
('¿Qué fabricante italiano de automóviles deportivos produce el 488 GTB?', 'Ferrari', 'Coches', 1),
('¿Cuál es el modelo de automóvil eléctrico más vendido hasta 2022?', 'Tesla Model 3', 'Coches', 3),
('¿Qué automóvil de músculo es conocido como el "Pony Car"?', 'Ford Mustang', 'Coches', 2),
('¿Cuál es el nombre de la compañía de automóviles eléctricos de Elon Musk?', 'Tesla', 'Coches', 1),
('¿Qué fabricante de automóviles alemán produce el deportivo 911?', 'Porsche', 'Coches', 1),
('¿Qué significa el acrónimo AWD?', 'Tracción en las Cuatro Ruedas', 'Coches', 5),
('¿Qué ciudad es conocida por su feria automotriz y se considera la cuna de la industria automotriz?', 'Detroit', 'Coches', 1),
('¿Cuál es el término común para el adorno decorativo del capó de un automóvil?', 'Mascota o Adorno del Capó', 'Coches', 5),
('¿Qué fabricante de automóviles japonés produce los modelos Civic y Accord?', 'Honda', 'Coches', 1),
('¿Cuál es el propósito del convertidor catalítico en un automóvil?', 'Convierte los contaminantes nocivos en sustancias menos dañinas', 'Coches', 8),
('¿Qué icónica compañía estadounidense produce los modelos Silverado y Camaro?', 'Chevrolet', 'Coches', 1),
('¿En qué año debutó el Volkswagen Beetle?', '1938', 'Coches', 1),
('¿Qué marca de automóviles de lujo presenta un famoso emblema alado con las letras "RR"?', 'Rolls-Royce', 'Coches', 1),
('¿Cuál es la función principal del alternador de un automóvil?', 'Genera energía eléctrica para los sistemas del vehículo', 'Coches', 7),
('¿En qué país se encuentra la sede de la icónica marca de automóviles Volvo?', 'Suecia', 'Coches', 1),
('¿Qué mide el término "caballos de fuerza" en el motor de un automóvil?', 'Potencia o rendimiento del motor', 'Coches', 5),
('¿Qué fabricante de automóviles italiano produce los modelos Huracan y Aventador?', 'Lamborghini', 'Coches', 1),
('¿Cuál es el propósito del diferencial en el tren motriz de un automóvil?', 'Permite que las ruedas giren a diferentes velocidades al girar', 'Coches', 10),
('¿Qué fabricante de automóviles estadounidense es conocido por su serie de camiones Ram?', 'Ram (una división de Stellantis)', 'Coches', 5),
('¿Cuál es el modelo de automóvil más vendido en la historia?', 'Toyota Corolla', 'Coches', 2),
('¿Qué marca de automóviles de lujo es conocida por su mascota "Spirit of Ecstasy"?', 'Rolls-Royce', 'Coches', 1),
('¿Cuál es el rango máximo del Tesla Model S Plaid hasta 2022?', 'Aproximadamente 390 millas (628 km)', 'Coches', 6),
('¿Qué fabricante de automóviles asiático produce los modelos Sonata y Elantra?', 'Hyundai', 'Coches', 1),
('¿A qué se refiere el término "híbrido" en el contexto de los automóviles?', 'Un vehículo que combina un motor de combustión interna con un motor eléctrico', 'Coches', 12),
('¿Qué serie de carreras presenta el famoso Gran Premio de Mónaco?', 'Fórmula 1', 'Coches', 2),
('¿Cuál es el nombre de la tecnología de conducción autónoma desarrollada por Tesla?', 'Autopilot', 'Coches', 1),
('¿En qué ciudad italiana se encuentra la sede de Ferrari?', 'Maranello', 'Coches', 1),
('¿Cuál es la velocidad máxima del Koenigsegg Jesko Absolut?', '330 mph (531 km/h)', 'Coches', 6),
('¿Qué fabricante de automóviles japonés produce los modelos Pathfinder y Rogue?', 'Nissan', 'Coches', 1),
('¿Cuál es el propósito de un bloqueo diferencial en un automóvil?', 'Bloquea el diferencial para proporcionar un par igual a ambas ruedas', 'Coches', 12),
('¿Qué icónico automóvil de músculo estadounidense presenta un león rugiente como su logotipo?', 'Dodge Challenger', 'Coches', 2),
('¿Cuál es la velocidad máxima del McLaren Speedtail?', '250 mph (402 km/h)', 'Coches', 6),
('¿Qué fabricante de automóviles alemán produce los modelos X5 y Serie 3?', 'BMW', 'Coches', 1),
('¿Cuál es el nombre de la famosa carrera de resistencia celebrada anualmente en Francia?', '24 Horas de Le Mans', 'Coches', 5),
('¿Qué compañía de automóviles eléctricos es conocida por su Roadster, Model S y Cybertruck?', 'Tesla', 'Coches', 1),
('¿Cuál es la función principal del radiador de un automóvil?', 'Enfriar el motor disipando el calor del refrigerante', 'Coches', 9),
('¿Qué fabricante de automóviles japonés produce los modelos Outback y Forester?', 'Subaru', 'Coches', 1),
('¿A qué se refiere el término "turbocharger" en el motor de un automóvil?', 'Aumenta la eficiencia y potencia del motor al forzar más aire hacia la cámara de combustión', 'Coches', 19),
('¿Qué fabricante de automóviles británico produce los modelos F-Type e I-PACE?', 'Jaguar', 'Coches', 1),
('¿Cuál es el propósito de un alerón de un automóvil?', 'Mejora la aerodinámica y proporciona una mejor estabilidad', 'Coches', 9),
('¿Qué marca de automóviles de lujo es conocida por su emblema de tres puntas?', 'Mercedes-Benz', 'Coches', 1);
